services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        GITHUB_USERNAME: ${GITHUB_USERNAME}
    container_name: skill-repeater-web
    restart: always
    environment:
      MICRONAUT_ENVIRONMENTS: prod
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      DATASOURCE_URL: jdbc:postgresql://skill-repeater-db:5432/${SKILL_REPEATER_DATABASE_NAME}
      DATASOURCE_USERNAME: ${SKILL_REPEATER_DATABASE_USER}
      DATASOURCE_PASSWORD: ${SKILL_REPEATER_DATABASE_PASSWORD}
      JWT_GENERATOR_SIGNATURE_SECRET: ${JWT_GENERATOR_SIGNATURE_SECRET}
      # Jaeger configuration
      JAEGER_SERVICE_NAME: user-service
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    ports:
      - "8095:8095"
      - "5006:5006"  # Debug port
    # Add -internal DNS aliases to match Kubernetes service names
    extra_hosts:
      - "user-service-internal:user-service"
      - "email-service-internal:email-service"
      - "auth-service-internal:auth-service"
      - "email-template-service-internal:email-template-service"
