openapi: 3.0.1
info:
  title: user-service
  description: User service for operating user processes
  contact:
    name: Dimitri Posadskiy
    url: https://posadskiy.com
    email: support@posadskiy.com
  license:
    name: MIT
    url: https://opensource.org/license/mit
  version: "0.1"
paths:
  /signup:
    post:
      operationId: registration
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDto"
        required: true
      responses:
        "200":
          description: registration 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"
  /v0/user/{id}:
    get:
      operationId: getUserById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: getUserById 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"
components:
  schemas:
    UserDto:
      required:
      - email
      - password
      - username
      type: object
      properties:
        id:
          type: string
          nullable: true
        username:
          minLength: 1
          type: string
        email:
          type: string
        password:
          type: string
