#tag::micronaut[]
micronaut:
  application:
    name: user-service
  server:
    port: 8095
#end::micronaut[]

#tag::database[]
datasources:
  default:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
#end::database[]

#tag::jaeger[]
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1 # <1>
    http-sender:
      url: http://jaeger:14268/api/traces
#end::jaeger[]
