#tag::micronaut[]
micronaut:
  application:
    name: user-service
  server:
    port: 8095
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - http://localhost:3000
  security:
    enabled: true
    intercept-url-map:
      - pattern: /swagger-ui/**
        access: isAnonymous()
      - pattern: /swagger/**
        access: isAnonymous()
      - pattern: /v3/api-docs/**
        access: isAnonymous()
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET}"
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
#end::micronaut[]

#tag::database[]
datasources:
  default:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
#end::database[]

#tag::zipkin[]
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 1 # <1>
#end::zipkin[]
